name: build
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build services
        run: docker-compose up -d
      - name: List container
        run: docker-compose ps
      - name: Test Wordpress container
        run: docker run --rm appropriate/curl -s --retry 3 --retry-connrefused https://www.google.com/
      - name: Test PhpMyAdmin container
        run: docker run --rm appropriate/curl -s --retry 3 --retry-connrefused http://127.0.0.1:8888/
